### ISSUE TITLE
Play music on Android simulator for macOS

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#37]
We get an error as follows on Android simulator for macOS:
```
Possible EventEmitter memory leak detected. 11 getDuration listeners added. Use emitter.setMaxListeners() to increase limit
at MusicRoom/node_modules/events/events.js:208:6 in _addListener
at MusicRoom/node_modules/events/events.js:256:2 in once
at MusicRoom/node_modules/react-native-youtube-iframe/dist/YoutubeIframe.js:1:3363 in Promise$argument_0
at MusicRoom/node_modules/react-native-youtube-iframe/dist/YoutubeIframe.js:1:3260 in getDuration
at components/TheMusicPlayer.tsx:319:4 in fetchMusicPlayerTotalDuration
at components/TheMusicPlayer.tsx:319:4 in fetchMusicPlayerTotalDuration
at components/TheMusicPlayer.tsx:280:44 in setInterval$argument_0
at components/TheMusicPlayer.tsx:280:44 in setInterval$argument_0
at [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by Devessier** [comment]
It seems that the webview can not load the player. We get the following error:

```json
{
  "canGoBack": false,
  "canGoForward": false,
  "code": -2,
  "description": "net::ERR_NAME_NOT_RESOLVED",
  "loading": false,
  "target": 33,
  "title": "",
  "url": "https://lonelycpp.github.io/react-native-youtube-iframe/iframe.html?data=%7B%22rel_s%22:0,%22loop_s%22:0,%22videoId_s%22:%2255SwKPVMVM4%22,%22controls_s%22:1,%22contentScale_s%22:1,%22cc_lang_pref_s%22:%22%22,%22allowWebViewZoom%22:false,%22modestbranding_s%22:0,%22preventFullScreen_s%22:1,%22showClosedCaptions_s%22:0%7D",
}
```

It seems to be a known issue: https://github.com/react-native-webview/react-native-webview/issues/1619.

**Comment by Devessier** [comment]
It turned out that I did not have access to internet inside my Android simulator.
I followed those instructions and now it works perfectly: https://stackoverflow.com/a/49332186.
